#find . -type f -not -path "./hm/*" -not -path "./module-list.nix" | grep .nix
[
./services/gnome-keyring/default.nix
./services/teamviewer.nix
./services/mpd/mpd-server.nix
./services/mpd/mpd-client.nix
./services/mpd/mpd-local.nix
./services/postgres.nix
./services/sshd.nix
./services/nfs/default.nix
./services/borgbackup/personal-main.nix
./services/borgbackup/personal-music.nix
./services/githubrunner.nix
./services/syncthing.nix
./common/de/nonei3.nix
./common/de/xfce.nix
./common/de/xfcei3.nix
./common/packages-system.nix
./common/bootloader-uefi.nix
./common/hardware-default-intel.nix
./common/locale-dk.nix
./common/security.nix
./common/services.nix
./common/sound.nix
./common/nix.nix
./common/xorg.nix
./users/work.nix
./users/servuser.nix
./users/personal.nix
./virtualisation/docker.nix
./virtualisation/virtualbox.nix
]
