#find . -type f -not -path "./hm/*" -not -path "./module-list.nix" | grep .nix
[
./common/bootloader-uefi.nix
./common/de/nonei3.nix
./common/de/xfce.nix
./common/de/xfcei3.nix
./common/hardware-default-intel.nix
./common/locale-dk.nix
./common/nix.nix
./common/packages-system.nix
./common/security.nix
./common/services.nix
./common/sound.nix
./common/xorg.nix
./services/borgbackup/personal-main.nix
./services/borgbackup/personal-music.nix
./services/githubrunner/default.nix
./services/gnome-keyring/default.nix
./services/mpd/mpd-client.nix
./services/mpd/mpd-local.nix
./services/mpd/mpd-server.nix
./services/nfs/default.nix
./services/postgres/default.nix
./services/sshd/default.nix
./services/teamviewer/default.nix
./users/guest.nix
./users/personal.nix
./users/servuser.nix
./users/work.nix
./virtualisation/docker/default.nix
./virtualisation/virtualbox/default.nix
]
